title = "Unsafe"
slides = "11_unsafe"
book_chapters = ["ch20-01-unsafe-rust"]

[[videos]]
title = "The Rust Programming Language Book"
items = [
    "https://www.youtube.com/watch?v=9E2v8pCUc48&list=PLai5B987bZ9CoVR-QEIN9foz4QCJ0H2Y8",
]

[[videos]]
title = "Crust of Rust"
items = [
    "https://www.youtube.com/watch?v=8O0Nt9qY_vo&list=PLqbS7AVVErFiWDOAVrPt7aYmnuuOLYvOa",
    "https://www.youtube.com/watch?v=pePqWoTnSmQ&list=PLqbS7AVVErFiWDOAVrPt7aYmnuuOLYvOa",
]

[[videos]]
title = "Code to the Moon"
items = [
    "https://www.youtube.com/watch?v=HwupNf9iCJk&list=PL2q9pua8FpiUiCv6KmWWhR5Bh8GfElo98",
]

[[videos]]
title = "Low Level Learning Rust Talks"
items = [
    "https://www.youtube.com/watch?v=z_RekEdKcfk&list=PLc7W4b0WHTAUAEAguiqpNa5H0QqXJIJI6",
]

[[extras]]
title = "The Rustonomicon"
url = "https://doc.rust-lang.org/nomicon/"
